version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: adoptemos-db
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    image: adoptemos-server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    stdin_open: true
    tty: true

volumes:
  db: