version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: $MONGODB_NAME
    hostname: $MONGODB_HOST
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    image: $APP_NAME
    restart: unless-stopped
    container_name: $APP_NAME
    env_file: ./.env
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src

volumes:
  db:
