FROM node:18.14.0 AS build

WORKDIR /adoptemos-server
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM node:18.14.0-slim

WORKDIR /adoptemos-server
COPY --from=build /adoptemos-server ./

EXPOSE 8080
