FROM node:20.9 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM node:20.9-bullseye-slim

WORKDIR /app
COPY --from=build /app ./

EXPOSE $PORT

CMD npm start
