FROM node:20.9 AS build

WORKDIR /adoptemos-server
COPY package*.json ./
RUN npm install --ci
COPY . .

RUN npm run build

FROM node:20.9-slim

WORKDIR /adoptemos-server
COPY --from=build /adoptemos-server ./

EXPOSE 8080
