FROM node:20.9 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build
RUN node scripts/buildMigrations.js

FROM node:20.9-bullseye-slim

ENV IS_DOCKER=true

WORKDIR /app
COPY --from=build /app ./

EXPOSE $PORT

CMD node scripts/migrateDb.js up --container && npm start
