FROM node:20.9 AS build

WORKDIR /adoptemos-server
COPY package*.json ./
RUN npm install --ci
COPY . .

RUN npm run build

FROM node:20.9-bullseye-slim

WORKDIR /adoptemos-server
COPY --from=build /adoptemos-server ./

RUN apt-get update && apt-get install -y libssl1.1
RUN apt-get install -y libcurl4

EXPOSE 8080
