name: Build image
on: workflow_call
jobs:
  build-image-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.ci
          tags: ${{ secrets.APP_NAME }}
          outputs: type=docker,dest=/tmp/${{ secrets.APP_NAME }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ secrets.APP_NAME }}
          path: /tmp/${{ secrets.APP_NAME }}.tar
