name: Deploy
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
          -d '{"serviceName": "${{ secrets.APP_NAME }}"}'
