name: End to End Tests
on: workflow_call
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      FIREBASE_BUCKET_URL: ${{ secrets.FIREBASE_BUCKET_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up docker containers
        uses: ./.github/actions/run-containers
        with:
          image-name: ${{ secrets.APP_NAME }}
      - name: Run end to end tests
        run: |
          docker exec ${{ secrets.APP_NAME }} npm run test-e2e
