name: Integration Tests
on: workflow_call
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up docker containers
        uses: ./.github/actions/run-containers
        with:
          image-name: ${{ secrets.APP_NAME }}
      - name: Run integration tests
        run: |
          docker exec ${{ secrets.APP_NAME }} npm run test-integration
