name: Merge to main workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [Branch push workflow.test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: adoptemos-server
          heroku_email: "jackblakeston93@gmail.com"
