name: CICD workflow

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.ci
          tags: adoptemos-server
          outputs: type=docker,dest=/tmp/adoptemos-server.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: adoptemos-server
          path: /tmp/adoptemos-server.tar

  test:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: adoptemos-server
          path: /tmp

      - name: create env file
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo MONGODB_NAME=${{ secrets.MONGODB_NAME }} >> .env
          echo MONGODB_HOST=${{ secrets.MONGODB_HOST }} >> .env
          echo MONGODB_PORT=${{ secrets.MONGODB_PORT }} >> .env
          echo MONGODB_USER=${{ secrets.MONGODB_USER }} >> .env
          echo MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} >> .env

      - name: Load image
        run: docker load --input /tmp/adoptemos-server.tar

      - name: Start containers
        run: npm run docker-up

      - name: Run tests
        run: |
          docker exec adoptemos-server npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: "jackblakeston93@gmail.com"

      - name: Build and push Docker image
        run: |
          docker build -t registry.heroku.com/adoptemos-server/web -f dockerfiles/Dockerfile.deploy .
          docker push registry.heroku.com/adoptemos-server/web

      - name: Deploy to Heroku
        run: |
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}  heroku container:release web -a adoptemos-server
