name: On main branch merge

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit

  validate:
    needs: [build]
    uses: ./.github/workflows/validate-code.yml
    secrets: inherit

  unit-tests:
    needs: [build]
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  integration-tests:
    needs: [build]
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  e2e-tests:
    needs: [build]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit

  deploy:
    needs: [validate, unit-tests, integration-tests, e2e-tests]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
