name: On feature branch push

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit

  unit-tests:
    needs: [build]
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  integration-tests:
    needs: [build]
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
